### ISSUE TITLE
TypeError: Query.join() takes from 2 to 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by voiplab-niu** [IoTtalk/Dummy_Device_IoTtalk_v1_py#16]
您好我是懷恩老師實驗室的同學 我在使用這個測試檔測試我的iottalk1.5時遇到了以上問題 我該怎麼去解決它呢?
![image](https://github.com/user-attachments/assets/2bee2bcf-afd0-471c-94c2-71b2cfce141b)

**Comment by Jyneda** [comment]
IoTtalk server自己裝的?  你要不要先試試看這台主機   https://class.iottalk.tw   你那個訊息應該是server沒裝好。

**Comment by voiplab-niu** [comment]
好的 那我晚點嘗試一下

Jyneda ***@***.***> 於 2024年7月16日 週二 22:34 寫道：

**Comment by voiplab-niu** [comment]
不好意思隔這麼久才來詢問 那請問 MQTT_User 、MQTT_PW 分別應該填入什麼呢

![image](https://github.com/user-attachments/assets/65fe6012-25a9-4d08-8593-1a22b37673e0)

**Comment by voiplab-niu** [comment]
還是是我誤會這個檔案 不是只改這邊就能使用

**Comment by voiplab-niu** [comment]
因為我們最終還是需要架一個iottalk1.5 架在宜大 但奈何我現在還不知道怎麼解決我的架設問題 
如果方便還是我也可以跟您拿聯絡方式

**Comment by Jyneda** [comment]
確實只要修改SA.py即可，只是你內容填錯了。  你不知道我的信箱?  你可以問問陳老師，或是 你信箱留給我。

**Comment by voiplab-niu** [comment]
是的 因為之前都是透過靈璽學姊將老師邀進線上會議室 我其實連一平老師的信箱也沒有 哈哈..
那想請教一下 老師如果是這樣 我現在是只能重架嗎 還是我應該去檢查哪個部分..

我的email : r1243013@ems.niu.edu.tw
